TechnicalService/TechnicalService.WebMVC.UI/Areas/Management/Controllers/OperatorController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web.Mvc;
using TechnicalService.BLL.Account;
using static TechnicalService.BLL.Repository.Repository;

namespace TechnicalService.WebMVC.UI.Areas.Management.Controllers
{
    [Authorize(Roles = "Operatör,Admin")]
    public class OperatorController : Controller
    {
        // GET: Management/Operator
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FaultList(int type=0)
        {
            ViewBag.Technician = MembershipTools.GetTechnician();
            if (type == 0)
                ViewBag.OperatorID = null;
            else
            ViewBag.OperatorID = System.Web.HttpContext.Current.User.Identity.GetUserId();
            var model = new FaultRepo().GetAll();
            return View(model);
        }
        public ActionResult Details(int id)
        {
           
           var faultRepo= new FaultRepo();
            var Fault=faultRepo.GetById(id);

            return View(Fault);
        }


    }
}

TechnicalService/TechnicalService.WebMVC.UI/Areas/Management/Controllers/TechnicianController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TechnicalService.BLL.Account;
using static TechnicalService.BLL.Repository.Repository;

namespace TechnicalService.WebMVC.UI.Areas.Management.Controllers
{
    [Authorize(Roles = "Teknisyen")]
    public class TechnicianController : Controller
    {
        // GET: Management/Technician
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FaultList()
        {

            var model = new FaultRepo().GetAll().Where(x => x.TechnicianID == MembershipTools.GetUser().Id).ToList();
            return View(model);
        }
     
        public ActionResult Edit(int id)
        {
            var model = new FaultRepo().GetById(id);

            return View(model);
        }
    }
}

TechnicalService/TechnicalService.WebMVC.UI/Controllers/FaultController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TechnicalService.BLL.Account;
using TechnicalService.BLL.Settings;
using TechnicalService.Entity.Entities.Fault;
using TechnicalService.Entity.Enums;
using TechnicalService.Entity.ViewsModel;
using static TechnicalService.BLL.Repository.Repository;

namespace TechnicalService.WebMVC.UI.Controllers
{
    public class FaultController : UserBaseController
    {
        public ActionResult FaultReport()

        {
            var Categories = CategoriSelectList();
            var Brands = BrandSelectList();
            ViewBag.Brands = Brands;
            ViewBag.Categories = Categories;
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FaultReport(FaultViewModel model)
        {
        


            if (model == null)
                return RedirectToAction("FaultReport");
            Fault NewFault = new Fault()
            {
                 ModelID=model.ModelID,
                UserID = MembershipTools.GetUser().Id,
                Description = model.Description,
                Address = model.AddressDescription,
                Title = model.Title,
                lat = model.lat,
                lng = model.lng,
                InvoiceCode = model.InvoiceCode,
                AppointmentDate = model.TransactionDate
                
                 
            };
            var Categories = CategoriSelectList();
            var Brands = BrandSelectList();
            ViewBag.Brands = Brands;
            ViewBag.Categories = Categories;
            try
            {
                new FaultRepo().Insert(NewFault);
                if (model.Fault_Photos.Any())
                {
                    foreach (var dosya in model.Fault_Photos)
                    {
                        if (dosya != null && dosya.ContentType.Contains("image") && dosya.ContentLength > 0)
                        {
                            string fileName = Path.GetFileNameWithoutExtension(dosya.FileName);
                            string extName = Path.GetExtension(dosya.FileName);
                            fileName = SiteSettings.UrlFormatConverter(fileName);
                            fileName += Guid.NewGuid().ToString().Replace("-", "");
                            var directoryPath = Server.MapPath("~/Uploads/ArizaImage");
                            var filePath = Server.MapPath("~/Uploads/ArizaImage/") + fileName + extName;
                            if (!Directory.Exists(directoryPath))
                                Directory.CreateDirectory(directoryPath);
                            dosya.SaveAs(filePath);
                            ImageResize(400, 300, filePath);
                            new FaultPhotoRepo().Insert(new Fault_Photo()
                            {
                                FaultID = NewFault.ID,
                                URL = @"/Uploads/FaultImage/" + fileName + extName
                            });
                        }
                    }
                }
                Fault_Status NewFault_Status = new Fault_Status() //Ariza durumunu oluşturuldu olarak ekle
                {
                    Status = FaultStatus.Olusturuldu,
                    Description = "Arıza  oluşturuldu.",
                    FaultID = NewFault.ID
                };
                NewFault.Statuses.Add(NewFault_Status);
                
                new FaultRepo().Update();
                ViewBag.sonuc = "Kayıt Başarılı";

                return View();
            }
            catch (Exception ex)
            {
                ViewBag.sonuc = "Arıza kaydedilirken beklenmeyen bir hata oluştu. > " + ex.Message;
                return View();
            }


        }

        public ActionResult Faults()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Login", "Account");
            var faults = new FaultRepo().GetAll().Where(x=>x.UserID==User.Identity.GetUserId()).ToList();
            if (TempData["Sonuc"] != null)
            {
                ViewBag.Sonuc = TempData["Sonuc"];
                TempData.Remove("Sonuc");
            }

            return View(faults);
        }

        public ActionResult Delete(int id)
        {
            var faultrepo = new FaultRepo();
            var fault=faultrepo.GetById(id);

            try
            {

                faultrepo.Delete(fault);
                
            }
            catch (Exception ex)
            {
                TempData["Sonuc"] = "Arıza Silinemedi" + ex.Message;
                return RedirectToAction("Faults");
            }
            TempData["Sonuc"] = "Arıza Silindi";
            return RedirectToAction("Faults");


        }


    }
}

TechnicalService/TechnicalService.WebMVC.UI/Views/Shared/_PartialAccountSidebar.cshtml
<div class="panel panel-default sidebar-menu">

    <div class="panel-heading">
        <h3 class="panel-title">Customer section</h3>
    </div>

    <div class="panel-body">

        <ul class="nav nav-pills nav-stacked">
            
            @if (HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "UpdatePassword")
            {

                <li class="active">
                    <a href="../Account/UpdatePassword"><i class="fa fa-list"></i>Şifreyi Güncelle</a>
                </li>
            }
            else
            {

                <li>
                    <a href="../Account/UpdatePassword"><i class="fa fa-list"></i>Şifreyi Güncelle</a>
                </li>
            }
                
                   
        
           
                @if (HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "Profile")
                {

                    <li class="active">
                        <a href="../Account/Profile"><i class="fa fa-user"></i> Profil</a>
                    </li>
                }
                else
                {
                    <li >
                        <a href="../Account/Profile"><i class="fa fa-user"></i> Profil</a>
                    </li>
                }
                   
                
                <li>
                 <a href="../Account/Logout"><i class="fa fa-sign-out"></i> Çıkış Yap</a>
                    </li>
        </ul>
    </div>

</div>

TechnicalService/TechnicalService.WebMVC.UI/Views/Shared/_PartialBottomHeader.cshtml
@if (HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString() != "Home" || @HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() != "Index")
{
<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>@HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString()</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb">
                    <li> 
                        <a href="../@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()">@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()</a>
                    </li>
                    <li>@HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString()</li>
                </ul>

            </div>
        </div>
    </div>
</div>
}

TechnicalService/TechnicalService.WebMVC.UI/Views/Shared/_PartialCopyright.cshtml
<div id="copyright">
    <div class="container">
        <div class="col-md-12">
            <p class="pull-left">&copy; 2018. CSK Teknik Servis</p>
            <p class="pull-right"></p>
           
        </div>
    </div>
</div>

TechnicalService/TechnicalService.WebMVC.UI/Views/Shared/_PartialFooter.cshtml
<footer id="footer">
    <div class="container">
        <div class="col-md-3 col-sm-6">
            <h4>About us</h4>

            <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>

            <hr>

            <h4>Join our monthly newsletter</h4>

            <form>
                <div class="input-group">

                    <input type="text" class="form-control">

                    <span class="input-group-btn">

                        <button class="btn btn-default" type="button"><i class="fa fa-send"></i></button>

                    </span>

                </div>
                <!-- /input-group -->
            </form>

            <hr class="hidden-md hidden-lg hidden-sm">

        </div>
        <!-- /.col-md-3 -->

        <div class="col-md-3 col-sm-6">

            <h4>Blog</h4>

            <div class="blog-entries">
                <div class="item same-height-row clearfix">
                    <div class="image same-height-always">
                        <a href="#">
                            <img class="img-responsive" src="../images/detailsquare.jpg" alt="">
                        </a>
                    </div>
                    <div class="name same-height-always">
                        <h5><a href="#">Blog post name</a></h5>
                    </div>
                </div>

                <div class="item same-height-row clearfix">
                    <div class="image same-height-always">
                        <a href="#">
                            <img class="img-responsive" src="../images/detailsquare.jpg" alt="">
                        </a>
                    </div>
                    <div class="name same-height-always">
                        <h5><a href="#">Blog post name</a></h5>
                    </div>
                </div>

                <div class="item same-height-row clearfix">
                    <div class="image same-height-always">
                        <a href="#">
                            <img class="img-responsive" src="../images/detailsquare.jpg" alt="">
                        </a>
                    </div>
                    <div class="name same-height-always">
                        <h5><a href="#">Very very long blog post name</a></h5>
                    </div>
                </div>
            </div>

            <hr class="hidden-md hidden-lg">

        </div>
        <!-- /.col-md-3 -->

        <div class="col-md-3 col-sm-6">

            <h4>Contact</h4>

            <p>
                <strong>Universal Ltd.</strong>
                <br>13/25 New Avenue
                <br>Newtown upon River
                <br>45Y 73J
                <br>England
                <br>
                <strong>Great Britain</strong>
            </p>

            <a href="contact.html" class="btn btn-small btn-template-main">Go to contact page</a>

            <hr class="hidden-md hidden-lg hidden-sm">

        </div>
        <!-- /.col-md-3 -->



        <div class="col-md-3 col-sm-6">

            <h4>Photostream</h4>

            <div class="photostream">
                <div>
                    <a href="#">
                        <img src="../images/detailsquare.jpg" class="img-responsive" alt="#">
                    </a>
                </div>
                <div>
                    <a href="#">
                        <img src="../images/detailsquare2.jpg" class="img-responsive" alt="#">
                    </a>
                </div>
                <div>
                    <a href="#">
                        <img src="../images/detailsquare3.jpg" class="img-responsive" alt="#">
                    </a>
                </div>
                <div>
                    <a href="#">
                        <img src="../images/detailsquare3.jpg" class="img-responsive" alt="#">
                    </a>
                </div>
                <div>
                    <a href="#">
                        <img src="../images/detailsquare2.jpg" class="img-responsive" alt="#">
                    </a>
                </div>
                <div>
                    <a href="#">
                        <img src="../images/detailsquare.jpg" class="img-responsive" alt="#">
                    </a>
                </div>
            </div>

        </div>
        <!-- /.col-md-3 -->
    </div>
    <!-- /.container -->
</footer>

TechnicalService/TechnicalService.WebMVC.UI/Views/Shared/_PartialHeader.cshtml
@using Microsoft.AspNet.Identity
@using TechnicalService.BLL.Account
<header>

    <!-- *** TOP ***
    _________________________________________________________ -->
    <div id="top">
        <div class="container">
            <div class="row">
                <div class="col-xs-5 contact">
                    <p class="hidden-sm hidden-xs">0538 729 98 10 veya coskunhakan95@gmail.com adresinden bize ulaşın.</p>
                    <p class="hidden-md hidden-lg">
                        <a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>  <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
                    </p>
                </div>
                <div class="col-xs-7">
                   @if (User.Identity.GetUserId() != null)
                   {
                    if (HttpContext.Current.User.IsInRole("Operatör"))
                    {
                        <a type="button"  class="btn btn-template-primary" href="@Url.Action("FaultList", "Operator", new { Area = "Management" })">Operator Ekranı</a>
                    }
                    if (HttpContext.Current.User.IsInRole("Admin"))
                    {
                        <a type="button"  class="btn btn-template-primary" href="@Url.Action("UserManager", "Admin", new { Area = "Management" })">Admin Ekranı</a>
                    }
                    if (HttpContext.Current.User.IsInRole("Teknisyen"))
                    {
                        <a  type="button" class="btn btn-template-primary"  href="@Url.Action("FaultList", "Technician", new { Area = "Management" })"> Teknisyen Ekranı</a>
                        }
                    }
                    @Html.Partial("_PartialLogin")

                </div>
            </div>
        </div>
    </div>

    <!-- *** TOP END *** -->
    <!-- *** NAVBAR ***
    _________________________________________________________ -->
    <div class="navbar-affixed-top" data-spy="affix" data-offset-top="200">

        <div class="navbar navbar-default yamm" role="navigation" id="navbar">

            <div class="container">
                <div class="navbar-header">

                    <a class="navbar-brand home" href="@Url.Action("Index", "Home")">
                        <img src="../images/logo.png" class="hidden-xs hidden-sm">
                        <img src="../images/logo-small.png" class="visible-xs visible-sm"><span class="sr-only"></span>
                    </a>
                    <div class="navbar-buttons">
                        <button type="button" class="navbar-toggle btn-template-main" data-toggle="collapse" data-target="#navigation">
                            <span class="sr-only">Toggle navigation</span>
                            <i class="fa fa-align-justify"></i>
                        </button>
                    </div>
                </div>
                <!--/.navbar-header -->

                <div class="navbar-collapse collapse" id="navigation">

                    <ul class="nav navbar-nav navbar-right">

                        @if (HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "Index")
                        {
                            <li class="active">
                                <a href="@Url.Action("Index", "Home")" class="button">Anasayfa</a>

                            </li>
                        }
                        else
                        {

                            <li>
                                <a href="@Url.Action("Index", "Home")" class="button">Anasayfa</a>

                            </li>
                        }
                        @if (HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString() == "Account")
                        {
                            <li class="active">
                                <a href="@Url.Action("Profile", "Account")" class="button">Hesabım</a>

                            </li>
                        }
                        else
                        {

                            <li>
                                <a href="@Url.Action("Profile", "Account")" class="button">Hesabım</a>

                            </li>
                        }

                        <li class="dropdown">
                            <a href="javascript: void(0)" class="dropdown-toggle" data-toggle="dropdown">Arıza İşlemleri <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="@Url.Action("FaultReport","Fault")">Arıza Kaydı Oluştur</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Faults","Fault")">Arıza Kayıtlarım</a>
                                </li>
                               

                            </ul>
                        </li>



                        <li class="dropdown use-yamm yamm-fw">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hakkımızda <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <div class="yamm-content">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <img src="../images/page-1.jpg" class="img-responsive hidden-xs" alt="">
                                            </div>
                                            <div class="col-sm-3">
                                                <h5>Hizmetlerimiz</h5>
                                                <ul>
                                                    <li>
                                                        <a href="@Url.Action("Washing", "Home")">Çamaşır Makinesi Servisi </a>
                                                    </li>
                                                    <li>
                                                        <a href="@Url.Action("Dishwasher", "Home")">Bulaşık Makinesi Servisi</a>
                                                    </li>
                                                    <li>
                                                        <a href="@Url.Action("Fridge", "Home")">Buzdolabı Servisi</a>
                                                    </li>
                                                    <li>
                                                        <a href="@Url.Action("Air-Conditioner", "Home")">Klima Servisi</a>
                                                    </li>
                                                    <li>
                                                        <a href="@Url.Action("Combi", "Home")">Kombi Servisi</a>
                                                    </li>

                                                </ul>
                                            </div>
                                            <div class="col-sm-3">
                                                <h5>Hakkımızda</h5>
                                                <ul>
                                                    <li>
                                                        <a href="@Url.Action("Policy", "Home")">Politikamız </a>
                                                    </li>
                                                    <li>
                                                        <a href="@Url.Action("CustomerPolicy", "Home")">Müşteri Memnuniyet Politikamız</a>
                                                    </li>


                                                </ul>
                                            </div>

                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>


                        @if (HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "Contact")
                        {
                            <li class="active">
                                <a href="@Url.Action("Contact", "Home")" class="button">İletişim</a>

                            </li>
                        }
                        else
                        {

                            <li>
                                <a href="@Url.Action("Contact", "Home")" class="button">İletişim</a>

                            </li>
                        }
                    </ul>

                </div>
                <!--/.nav-collapse -->



                <div class="collapse clearfix" id="search">

                    <form class="navbar-form" role="search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search">
                            <span class="input-group-btn">

                                <button type="submit" class="btn btn-template-main"><i class="fa fa-search"></i></button>

                            </span>
                        </div>
                    </form>

                </div>
                <!--/.nav-collapse -->

            </div>


        </div>
        <!-- /#navbar -->

    </div>


    <!-- *** NAVBAR END *** -->

</header>

TechnicalService/TechnicalService.WebMVC.UI/Views/Shared/_PartialLogin.cshtml
@using Microsoft.AspNet.Identity



<div class="login">
    @if (Request.IsAuthenticated)
    {
        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        {
            @Html.AntiForgeryToken()


            <a href="../Account/Profile"><i class="fa fa-user"></i> <span class="hidden-xs text-uppercase">Merhaba @User.Identity.GetUserName()</span></a>
           

            <a href="../Account/Logout"><i class="fa fa-sign-out"></i> <span class="hidden-xs text-uppercase">Çıkış Yap</span></a>

        }
    }
    else
    {


        <a href="../Account/Login"><i class="fa fa-sign-in"></i> <span class="hidden-xs text-uppercase">Giriş Yap</span></a>
        <a href="../Account/Register"><i class="fa fa-user"></i> <span class="hidden-xs text-uppercase">Kayıt Ol</span></a>

    }
</div>

TechnicalService/TechnicalService.WebMVC.UI/Views/Shared/_PartialMaps.cshtml
<div class="map">
    <div id="google-map" class="map_model" data-zoom="11"></div>
    <ul class="map_locations">
        <li data-x="-73.9874068" data-y="40.643180" data-basic="../images/gmap_marker.png" data-active="../images/gmap_marker_active.png">
            <div class="location">
                <h3 class="txt-clr1">
                    BUSINESS
                    <small>
                        COMPANY
                    </small>
                </h3>
                <address>
                    <dl>
                        <dt>Free phone: </dt>
                        <dd class="phone"><a href="callto:#"> 800-2345-6789</a></dd>
                    </dl>
                    <dl>
                        <dt>Address: </dt>
                        <dd> 4578 Marmora Road,Glasgow D04 89GR</dd>
                    </dl>
                    <dl>
                        <dt>Hours: </dt>
                        <dd> 6am-4pm PST M-Th; &nbsp;&nbsp;  6am-3pm PST Fri</dd>
                    </dl>
                    <dl>
                        <dt> E-mail: </dt>
                        <dd><a href="mailto:#">info@demolink.org</a></dd>
                    </dl>
                </address>

            </div>
        </li>
        <li data-x="-74.100000" data-y="40.643180" data-basic="../images/gmap_marker2.png" data-active="../images/gmap_marker2_active.png">
            <div class="location">
                <h3 class="txt-clr1">
                    flooring
                    <small>
                        RETAILER
                    </small>
                </h3>
                <address>
                    <dl>
                        <dt>Free phone: </dt>
                        <dd class="phone"><a href="callto:#"> 800-2345-6789</a></dd>
                    </dl>
                    <dl>
                        <dt>Address: </dt>
                        <dd> 4578 Marmora Road,Glasgow D04 89GR</dd>
                    </dl>
                    <dl>
                        <dt>Hours: </dt>
                        <dd> 6am-4pm PST M-Th; &nbsp;&nbsp;  6am-3pm PST Fri</dd>
                    </dl>
                    <dl>
                        <dt> E-mail: </dt>
                        <dd><a href="mailto:#">info@demolink.org</a></dd>
                    </dl>
                </address>

            </div>
        </li>
        <li data-x="-73.8854068" data-y="40.693180" data-basic="../images/gmap_marker3.png" data-active="../images/gmap_marker3_active.png">
            <div class="location">
                <h3 class="txt-clr1">
                    flooring
                    <small>
                        RETAILER
                    </small>
                </h3>
                <address>
                    <dl>
                        <dt>Free phone: </dt>
                        <dd class="phone"><a href="callto:#"> 800-2345-6789</a></dd>
                    </dl>
                    <dl>
                        <dt>Address: </dt>
                        <dd> 4578 Marmora Road,Glasgow D04 89GR</dd>
                    </dl>
                    <dl>
                        <dt>Hours: </dt>
                        <dd> 6am-4pm PST M-Th; &nbsp;&nbsp;  6am-3pm PST Fri</dd>
                    </dl>
                    <dl>
                        <dt> E-mail: </dt>
                        <dd><a href="mailto:#">info@demolink.org</a></dd>
                    </dl>
                </address>

            </div>
        </li>
        <li data-x="-73.7874068" data-y="40.613180" data-basic="../images/gmap_marker4.png" data-active="../images/gmap_marker4_active.png">
            <div class="location">
                <h3 class="txt-clr1">
                    flooring
                    <small>
                        RETAILER
                    </small>
                </h3>
                <address>
                    <dl>
                        <dt>Free phone: </dt>
                        <dd class="phone"><a href="callto:#"> 800-2345-6789</a></dd>
                    </dl>
                    <dl>
                        <dt>Address: </dt>
                        <dd> 4578 Marmora Road,Glasgow D04 89GR</dd>
                    </dl>
                    <dl>
                        <dt>Hours: </dt>
                        <dd> 6am-4pm PST M-Th; &nbsp;&nbsp;  6am-3pm PST Fri</dd>
                    </dl>
                    <dl>
                        <dt> E-mail: </dt>
                        <dd><a href="mailto:#">info@demolink.org</a></dd>
                    </dl>
                </address>

            </div>
        </li>
        <li data-x="-74.200000" data-y="40.683180" data-basic="../images/gmap_marker5.png" data-active="../images/gmap_marker5_active.png">
            <div class="location">
                <h3 class="txt-clr1">
                    flooring
                    <small>
                        RETAILER
                    </small>
                </h3>
                <address>
                    <dl>
                        <dt>Free phone: </dt>
                        <dd class="phone"><a href="callto:#"> 800-2345-6789</a></dd>
                    </dl>
                    <dl>
                        <dt>Address: </dt>
                        <dd> 4578 Marmora Road,Glasgow D04 89GR</dd>
                    </dl>
                    <dl>
                        <dt>Hours: </dt>
                        <dd> 6am-4pm PST M-Th; &nbsp;&nbsp;  6am-3pm PST Fri</dd>
                    </dl>
                    <dl>
                        <dt> E-mail: </dt>
                        <dd><a href="mailto:#">info@demolink.org</a></dd>
                    </dl>
                </address>

            </div>
        </li>
    </ul>
</div>

TechnicalService/TechnicalService.WebMVC.UI/Views/Shared/_PartialSlider.cshtml
@model List<TechnicalService.Entity.Entities.Site.Slider>

<div class="home-carousel">

    <div class="dark-mask"></div>

    <div class="container">
        <div class="homepage owl-carousel">
@foreach (var item in Model)
{
            <div class="item">
                <div class="row">
                    <div class="col-sm-5 right">
                       
                        <h1>@item.Title</h1>
                        <p>
                            @item.Description
                        </p>
                    </div>
                    <div class="col-sm-7">
                        <img class="img-responsive" src="@item.PhotoUrl" alt="">
                    </div>
                </div>
            </div>
}
        </div>
        <!-- /.project owl-slider -->
    </div>
</div>